spring:
  datasource:
    url: ${USER_DB_URL}
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-ms: 360000000
  issuer: limited-edition-commerce-platform