spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URL}
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sparta.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: false
    locations: classpath:db/migration

server:
  port: 19030

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:
    tags:
      application: order-service

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-ms: 360000000
  issuer: limited-edition-commerce-platform

#product:
#  service:
#    url: ${PRODUCT_SERVICE_URL:http://localhost:19020}